### PR TITLE
Add commandline arguments

### PR DESCRIPTION
**Pull request by Hafeok**
The app generator now take two commandline arguments

1. SolutionType
  Can be either emptyHelix or pentiahelix
  If set the question for the type of solution will be skipped

2. SolutionName
  This sets the solution name and skips all other questions,
  setting them to their default values

### Description of the Change

This ensures that we can fill the settings when running the solution creation from scripts

### Benefits

This will benefit that we can create scripts that automatically generates an entire solution. 

### Possible Drawbacks

None.

### CODE REVIEW

**Review by Saturate — COMMENTED** [review]
I see some minor indentation issues on my side, could you fix them? Otherwise it looks great.

**Review by Saturate — CHANGES_REQUESTED** [review]
Indentation needs to be fixed :-)

**Comment by TakeitEasyAlan** [comment]
@Hafeok u going to fix the indentation?

**Comment by TakeitEasyAlan** [comment]
Should not contain more pentia specific tools

**Pull request closed without merging**
