### PR TITLE
Automatically install dependencies when choosing solution with Pentia tools

### PR DESCRIPTION
**Pull request by jimmah**
### Description of the Change

Added function to auto-install dependencies from NPM if the user chooses to scaffold a solution with Pentia tools.

### Benefits

Simplifies the process of getting the solution ready to use, the user doesn't have to issue `npm install` after running the generator.

### Possible Drawbacks

Users may not want dependencies automatically installing; in which case a prompt or switch option could be added to enable/disable this functionality.

### CODE REVIEW

**Comment by Saturate** [comment]
Thanks for the PR! Great contribution.

We talked it over a bit, and would like to see a checkbox in a step, so that the user can decide not to install it right away.

Maybe it could be checked by default, depends on @istern or @TakeitEasyAlan :)

**Comment by Saturate** [comment]
Thanks for the changes, I'll review it later again :-)

**Review by Saturate — APPROVED** [review]
Looks great now. Thanks for the contribution! :)

**Review by TakeitEasyAlan — APPROVED** [review]
Looks great thanks for the contribution :-)

**Pull request merged**
