### PR TITLE
Change Gulp version to 3.9.1 in package.json

### PR DESCRIPTION
**Pull request by Fillej**
"npm install gulp" supports up to version 3.9.1 of gulp.

### CODE REVIEW

**Comment by teltploek** [comment]
Hi @Fillej

Thank you for your contribution to the project.

To be able to secure traceability throughout the development process, we have decided early on, that we in this repository want to be able to provide a high level of insight into our decision making. This will not only improve the general quality of the product, but also make it easier to on-board contributors and secure momentum if everyone knows a bit about the context on the why's, how's and what's in the thought processes behind actions taken along the way.

Therefore we'll also be needing a description behind the motivation, or a user story, to understand the reason behind submitted pull requests. Could you please provide a bit of background information on the intend of this contribution?

Thank you very much.

/Brian

**Review by istern — APPROVED** [review]
I cant find a gulp version 3.9.5 so i think it is imporatant we fix this. as fast as possible.

**Comment by teltploek** [comment]
Oh now I understand. And you're right - there's no such version.

For some unknown reason @Hafeok changed it here:
https://github.com/PentiaLabs/generator-helix/commit/e220e2efc10b6e0ab42025c77d8459850549960f

I think we should just merge this right away.

**Comment by teltploek** [comment]
Merged, tagged and published to [npm](https://www.npmjs.com/package/generator-helix) as new patch, v1.0.8.

Thank you @Fillej for your contribution! 🦄  🇸🇪

**Pull request merged**
