### PR TITLE
Made part of the physicalRootPath depending on the layer name Fixes #72

### LINKED ISSUE #72: Layername is not used in the serialization.config
### User story
As a developer, I want the correct variabel to be used in serialization.config so that the serialized items end up in the correct folder.

### Expected behavior
The serialized items should end up in the foundation/feature/project folder.

### Actual behavior
The sc-variable thats being used is now hard coded to $(featureFolder). It should depend on the layer that's selected by the user.

### Steps to reproduce the behavior
yo helix:add
Select Project as layer.

The following is in the generated serialization.config file :
```
<targetDataStore
            physicalRootPath="$(featureFolder)\Login\$(configurationFolder)"
            useDataCache="false"
            type="Rainbow.Storage.SerializationFileSystemDataStore, Rainbow"
            singleInstance="true"
          />
```

### PR DESCRIPTION
**Pull request by saberone**
### Requirements

This fixes #72 

### Description of the Change

The _Serialization.config file was using a hard coded $(featureFolder) as part of the physicalRootPath

### Benefits

Bug should be fixed by this PR.

### Possible Drawbacks
Shiny happy people everywhere.

### CODE REVIEW

**Review by istern — APPROVED** [review]
Great catch.

**Review by Saturate — APPROVED** [review]

**Review by Saturate — CHANGES_REQUESTED** [review]
Does not seem to work for me.

**Comment by TakeitEasyAlan** [comment]
I also to get an error?

image

I have made a fixed this last night, please take a look @saberone

**Comment by saberone** [comment]
Odd. The error mess

**Comment by saberone** [comment]
Note to self. Don't comment and press wrong button.

But I tested it a couple of times and the error message seems odd. I didn't introduce a plus sign.

Anywayz. I'm closing this, again. The other pull request is a cleaner fix.

**Pull request closed without merging**
