### PR TITLE
Add contribution guidelines, and pr template

### PR DESCRIPTION
**Pull request by teltploek**
### Description of the Change

To make sure we get feature requests, issues, pull requests etc.
in as high quality as possible and to make everyone capable of
resolving them, I've added a set of contribution guidelines to let
contributors know what's expected of them.

Scope: docs, contributing, repository.

### Benefits

Other than that we'll have a clear and consise position on what's expected for contributors, the contributing.md will be visible when creating new issues (as you can see an example of here [here](https://github.com/blog/1184-contributing-guidelines)) and I've also created a PR-template that will prefill the textarea when people are submitting new pull requests.

### Possible Drawbacks

It might take longer for people to get into contributing, but the heightened quality will pay for that ;-)

### CODE REVIEW

**Review by Saturate — APPROVED** [review]
Looks great!

**Comment by kimschioett** [comment]
Fa'me prof, @teltploek, ihvertfald indholdsmæssigt. Hvordan kan man se, hvordan det kommer til at se ud herinde, før man merger?

**Comment by teltploek** [comment]
You can view the contribution.md in presentation mode right here:

https://github.com/PentiaLabs/generator-helix/pull/47/files?short_path=6a33714#diff-6a3371457528722a734f3c51d9238c13

**Review by istern — APPROVED** [review]

**Review by istern — APPROVED** [review]
Satme solidt

**Review by Hafeok — APPROVED** [review]
Love it - very well done. Lets get this bad boy merged!

**Pull request merged**
